### ISSUE TITLE
chore(passport): Apple hidden email not reachable by third-parties

### ISSUE THREAD

**Issue by betimshahini** [proofzero/rollupid#2706]
### Description

Apple email addresses using Apple's hidden email feature may not be reachable by third-party app developers, but only by the address registered when setting up the Rollup OAuth app with Apple. Investigate options, look at deterministic ways to identify when a hidden email is being used, and offer a warning to users related to restriction or to use our hidden email relay.

**Comment by picassobanana** [comment]
[Figma Link](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?type=design&node-id=16667-48073&mode=design&t=QurvtWvHTIBXVSYu-0)

**Tooltip:**
If you have enabled Apple’s Hide My Email the application being authorised will not be able to send emails to it, due to restrictions on Apple’s services. 

Consider using Rollup’s email masking instead by toggling it in the Email dropdown.


**Preview**
![Image](https://github.com/proofzero/rollupid/assets/103597761/f711ce9b-cb99-42c1-8432-475ac9084244)
